services:
  - type: web
    name: movilizacion-hcu
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: REACT_APP_SUPABASE_URL
        fromService:
          type: web
          name: movilizacion-hcu
          envVarKey: SUPABASE_URL
      - key: REACT_APP_SUPABASE_ANON_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
